-- CreateEnum
CREATE TYPE "ShiftType" AS ENUM ('ROUNDER', 'ADMIN', 'NIGHT_ADMIT_1', 'NIGHT_ADMIT_2');

-- CreateEnum
CREATE TYPE "ShiftPreference" AS ENUM ('MORE', 'FEWER', 'NEUTRAL');

-- CreateEnum
CREATE TYPE "AvailabilityType" AS ENUM ('UNAVAILABLE', 'PREFERRED');

-- CreateEnum
CREATE TYPE "ScheduleStatus" AS ENUM ('DRAFT', 'GENERATED', 'PUBLISHED');

-- CreateTable
CREATE TABLE "Physician" (
    "id" TEXT NOT NULL,
    "fullName" TEXT NOT NULL,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "desiredShifts" INTEGER NOT NULL DEFAULT 14,
    "minShifts" INTEGER NOT NULL DEFAULT 0,
    "maxShifts" INTEGER NOT NULL DEFAULT 20,
    "minRounding" INTEGER NOT NULL DEFAULT 0,
    "maxRounding" INTEGER NOT NULL DEFAULT 20,
    "minNights" INTEGER NOT NULL DEFAULT 0,
    "maxNights" INTEGER NOT NULL DEFAULT 8,
    "minAdmin" INTEGER NOT NULL DEFAULT 0,
    "maxAdmin" INTEGER NOT NULL DEFAULT 8,
    "shiftPreference" "ShiftPreference" NOT NULL DEFAULT 'NEUTRAL',
    "nightEligible" BOOLEAN NOT NULL DEFAULT true,
    "adminEligible" BOOLEAN NOT NULL DEFAULT true,
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Physician_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ScheduleMonth" (
    "id" TEXT NOT NULL,
    "year" INTEGER NOT NULL,
    "month" INTEGER NOT NULL,
    "status" "ScheduleStatus" NOT NULL DEFAULT 'DRAFT',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "generatedAt" TIMESTAMP(3),

    CONSTRAINT "ScheduleMonth_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ShiftAssignment" (
    "id" TEXT NOT NULL,
    "scheduleMonthId" TEXT NOT NULL,
    "date" TIMESTAMP(3) NOT NULL,
    "endDate" TIMESTAMP(3) NOT NULL,
    "shiftType" "ShiftType" NOT NULL,
    "rounderIndex" INTEGER,
    "startTime" TEXT NOT NULL,
    "endTime" TEXT NOT NULL,
    "physicianId" TEXT,
    "isManual" BOOLEAN NOT NULL DEFAULT false,
    "isLocked" BOOLEAN NOT NULL DEFAULT false,
    "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "warnings" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ShiftAssignment_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PhysicianAvailability" (
    "id" TEXT NOT NULL,
    "physicianId" TEXT NOT NULL,
    "date" TIMESTAMP(3) NOT NULL,
    "type" "AvailabilityType" NOT NULL,

    CONSTRAINT "PhysicianAvailability_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PhysicianPreference" (
    "id" TEXT NOT NULL,
    "physicianId" TEXT NOT NULL,
    "year" INTEGER NOT NULL,
    "month" INTEGER NOT NULL,
    "desiredShifts" INTEGER,
    "minShifts" INTEGER,
    "maxShifts" INTEGER,
    "notes" TEXT,

    CONSTRAINT "PhysicianPreference_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ScheduleGenerationRun" (
    "id" TEXT NOT NULL,
    "scheduleMonthId" TEXT NOT NULL,
    "startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "finishedAt" TIMESTAMP(3),
    "success" BOOLEAN NOT NULL DEFAULT false,
    "warnings" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "summary" JSONB,

    CONSTRAINT "ScheduleGenerationRun_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "ScheduleMonth_year_month_key" ON "ScheduleMonth"("year", "month");

-- CreateIndex
CREATE INDEX "ShiftAssignment_scheduleMonthId_idx" ON "ShiftAssignment"("scheduleMonthId");

-- CreateIndex
CREATE INDEX "ShiftAssignment_date_idx" ON "ShiftAssignment"("date");

-- CreateIndex
CREATE INDEX "PhysicianAvailability_physicianId_idx" ON "PhysicianAvailability"("physicianId");

-- CreateIndex
CREATE UNIQUE INDEX "PhysicianAvailability_physicianId_date_type_key" ON "PhysicianAvailability"("physicianId", "date", "type");

-- CreateIndex
CREATE UNIQUE INDEX "PhysicianPreference_physicianId_year_month_key" ON "PhysicianPreference"("physicianId", "year", "month");

-- CreateIndex
CREATE INDEX "ScheduleGenerationRun_scheduleMonthId_idx" ON "ScheduleGenerationRun"("scheduleMonthId");

-- AddForeignKey
ALTER TABLE "ShiftAssignment" ADD CONSTRAINT "ShiftAssignment_scheduleMonthId_fkey" FOREIGN KEY ("scheduleMonthId") REFERENCES "ScheduleMonth"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ShiftAssignment" ADD CONSTRAINT "ShiftAssignment_physicianId_fkey" FOREIGN KEY ("physicianId") REFERENCES "Physician"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PhysicianAvailability" ADD CONSTRAINT "PhysicianAvailability_physicianId_fkey" FOREIGN KEY ("physicianId") REFERENCES "Physician"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PhysicianPreference" ADD CONSTRAINT "PhysicianPreference_physicianId_fkey" FOREIGN KEY ("physicianId") REFERENCES "Physician"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ScheduleGenerationRun" ADD CONSTRAINT "ScheduleGenerationRun_scheduleMonthId_fkey" FOREIGN KEY ("scheduleMonthId") REFERENCES "ScheduleMonth"("id") ON DELETE CASCADE ON UPDATE CASCADE;

