import type {
  ShiftType,
  ShiftPreference,
  ScheduleStatus,
  Hospital,
} from "@prisma/client";

/** Physician as returned by GET /api/physicians (with date arrays). */
export interface PhysicianDTO {
  id: string;
  fullName: string;
  active: boolean;
  desiredShifts: number;
  minShifts: number;
  maxShifts: number;
  minRounding: number;
  maxRounding: number;
  minNights: number;
  maxNights: number;
  minAdmin: number;
  maxAdmin: number;
  shiftPreference: ShiftPreference;
  nightEligible: boolean;
  adminEligible: boolean;
  canWorkCarson: boolean;
  canWorkEaton: boolean;
  canWorkClinton: boolean;
  fteMultiplier: number;
  monthlyShiftTarget: number | null;
  maxConsecutiveDays: number;
  icsToken: string;
  notes: string | null;
  prefersNights: boolean;
  avoidsNights: boolean;
  prefersWeekends: boolean;
  avoidsWeekends: boolean;
  prefersDayAdmit: boolean;
  avoidsDayAdmit: boolean;
  avoidWeekdays: Record<string, boolean>;
  maxNightsPerMonth: number | null;
  maxWeekendsPerMonth: number | null;
  unavailableDates: string[];
  preferredDates: string[];
  timeOffDates: string[];
}

export interface AssignmentDTO {
  id: string;
  date: string;
  endDate: string;
  shiftType: ShiftType;
  hospital: Hospital;
  rounderIndex: number | null;
  startTime: string;
  endTime: string;
  physicianId: string | null;
  physicianName: string | null;
  isManual: boolean;
  isLocked: boolean;
  isAutoGenerated: boolean;
  warnings: string[];
}

export interface UnfilledSlotDTO {
  date: string;
  hospital: Hospital;
  shiftType: ShiftType;
  rounderIndex: number | null;
}

export interface GenerateResultDTO {
  warnings: string[];
  fairnessScore: number;
  unfilledSlots: UnfilledSlotDTO[];
}

export interface TimeOffDTO {
  id: string;
  date: string;
  note: string | null;
}

export interface PhysicianStatDTO {
  physicianId: string;
  fullName: string;
  total: number;
  rounding: number;
  admin: number;
  nights: number;
  weekends: number;
  holidays: number;
  desiredShifts: number;
  target: number;
  minShifts: number;
  maxShifts: number;
  belowMin: boolean;
  aboveMax: boolean;
  maxNightsPerMonth: number | null;
  maxWeekendsPerMonth: number | null;
}

export interface RunDTO {
  id: string;
  success: boolean;
  warnings: string[];
  summary: {
    fairnessScore: number;
    stats: PhysicianStatDTO[];
  } | null;
}

export interface MonthScheduleDTO {
  year: number;
  month: number;
  status: ScheduleStatus;
  generatedAt?: string | null;
  rounderCount: number;
  dayAdmitCount: number;
  nightAdmit1Count: number;
  nightAdmit2Count: number;
  carsonRounderCount: number;
  eatonRounderCount: number;
  clintonRounderCount: number;
  assignments: AssignmentDTO[];
  lastRun: RunDTO | null;
}
