import { NextResponse } from "next/server";
import type { Hospital, ShiftType } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { loadSchedulerPhysicians } from "@/lib/schedule-service";
import { toISODate, addDaysISO, isNightType } from "@/lib/scheduler";
import type { SchedulerPhysician } from "@/lib/scheduler";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

/** Minimal shape of the slot a physician would receive in a swap. */
interface Slot {
  date: string;
  endDate: string;
  shiftType: ShiftType;
  hospital: Hospital;
}

/** Per-physician working footprint built from their other assignments. */
interface Footprint {
  workingDates: Set<string>;
  nightStartDates: Set<string>;
}

/**
 * Swap the physicians of two assignments. Validates that BOTH resulting
 * assignments satisfy every hard constraint; rejects with a reason otherwise.
 */
export async function POST(req: Request) {
  const body = await req.json().catch(() => ({}));
  const aId = String(body.a ?? "");
  const bId = String(body.b ?? "");
  if (!aId || !bId || aId === bId) {
    return NextResponse.json(
      { error: "Two distinct assignment ids are required." },
      { status: 400 }
    );
  }

  const rows = await prisma.shiftAssignment.findMany({
    where: { id: { in: [aId, bId] } },
  });
  const a = rows.find((r) => r.id === aId);
  const b = rows.find((r) => r.id === bId);
  if (!a || !b) {
    return NextResponse.json({ error: "Assignment not found." }, { status: 404 });
  }

  const physicians = await loadSchedulerPhysicians();
  const byId = new Map(physicians.map((p) => [p.id, p]));

  const involved = [a.physicianId, b.physicianId].filter(
    (x): x is string => Boolean(x)
  );
  const others = involved.length
    ? await prisma.shiftAssignment.findMany({
        where: {
          physicianId: { in: involved },
          id: { notIn: [aId, bId] },
        },
        select: { physicianId: true, date: true, endDate: true, shiftType: true },
      })
    : [];

  const footprints = new Map<string, Footprint>();
  for (const id of involved) {
    footprints.set(id, { workingDates: new Set(), nightStartDates: new Set() });
  }
  for (const o of others) {
    const fp = footprints.get(o.physicianId!);
    if (!fp) continue;
    fp.workingDates.add(toISODate(o.date));
    fp.workingDates.add(toISODate(o.endDate));
    if (isNightType(o.shiftType)) fp.nightStartDates.add(toISODate(o.date));
  }

  const slotA: Slot = {
    date: toISODate(a.date),
    endDate: toISODate(a.endDate),
    shiftType: a.shiftType,
    hospital: a.hospital,
  };
  const slotB: Slot = {
    date: toISODate(b.date),
    endDate: toISODate(b.endDate),
    shiftType: b.shiftType,
    hospital: b.hospital,
  };

  // After the swap, B's physician takes A's slot and vice versa.
  const reasonA = validate(byId.get(b.physicianId ?? ""), slotA, footprints);
  const reasonB = validate(byId.get(a.physicianId ?? ""), slotB, footprints);
  if (reasonA || reasonB) {
    const parts = [reasonA, reasonB].filter(Boolean);
    return NextResponse.json(
      { error: `Swap not allowed: ${parts.join("; ")}` },
      { status: 400 }
    );
  }

  await prisma.$transaction([
    prisma.shiftAssignment.update({
      where: { id: aId },
      data: {
        physicianId: b.physicianId,
        isManual: Boolean(b.physicianId),
        isAutoGenerated: false,
        warnings: [],
      },
    }),
    prisma.shiftAssignment.update({
      where: { id: bId },
      data: {
        physicianId: a.physicianId,
        isManual: Boolean(a.physicianId),
        isAutoGenerated: false,
        warnings: [],
      },
    }),
  ]);

  return NextResponse.json({ ok: true });
}

/** Returns a human-readable reason the physician cannot take the slot, else null. */
function validate(
  phys: SchedulerPhysician | undefined,
  slot: Slot,
  footprints: Map<string, Footprint>
): string | null {
  // Moving INTO an empty slot (no incoming physician) is always permissible.
  if (!phys) return null;
  const who = phys.fullName;
  const fp = footprints.get(phys.id) ?? {
    workingDates: new Set<string>(),
    nightStartDates: new Set<string>(),
  };

  if (isNightType(slot.shiftType) && !phys.nightEligible) {
    return `${who} is not night eligible`;
  }
  if (slot.shiftType === "ADMIN" && !phys.adminEligible) {
    return `${who} is not day-admit eligible`;
  }
  if (slot.hospital !== "MAIN" && !phys.eligibleHospitals.has(slot.hospital)) {
    return `${who} is not eligible for that hospital`;
  }
  if (phys.timeOffDates.has(slot.date) || phys.unavailableDates.has(slot.date)) {
    return `${who} is off that day`;
  }
  if (fp.workingDates.has(slot.date) || fp.workingDates.has(slot.endDate)) {
    return `${who} already works that day`;
  }
  // Post-night rest looking back: a night on D-1 or D-2 blocks D.
  if (
    fp.nightStartDates.has(addDaysISO(slot.date, -1)) ||
    fp.nightStartDates.has(addDaysISO(slot.date, -2))
  ) {
    return `${who} is resting after a night shift`;
  }
  // Taking a night imposes its own two-day rest forward.
  if (isNightType(slot.shiftType)) {
    if (
      fp.workingDates.has(addDaysISO(slot.date, 1)) ||
      fp.workingDates.has(addDaysISO(slot.date, 2))
    ) {
      return `${who} works within the two-day rest after this night`;
    }
  }
  if (consecutiveSpan(fp.workingDates, slot.date) > phys.maxConsecutiveDays) {
    return `${who} would exceed ${phys.maxConsecutiveDays} consecutive days`;
  }
  return null;
}

function consecutiveSpan(working: Set<string>, date: string): number {
  let back = 0;
  let cursor = addDaysISO(date, -1);
  while (working.has(cursor)) {
    back += 1;
    cursor = addDaysISO(cursor, -1);
  }
  let fwd = 0;
  cursor = addDaysISO(date, 1);
  while (working.has(cursor)) {
    fwd += 1;
    cursor = addDaysISO(cursor, 1);
  }
  return back + fwd + 1;
}
