import type { ShiftType, ShiftPreference, Hospital } from "@prisma/client";

/**
 * A physician's scheduling profile — the subset of fields the scheduler
 * needs, plus precomputed availability sets keyed by ISO date string.
 */
export interface SchedulerPhysician {
  id: string;
  fullName: string;
  active: boolean;
  desiredShifts: number;
  minShifts: number;
  maxShifts: number;
  minRounding: number;
  maxRounding: number;
  minNights: number;
  maxNights: number;
  minAdmin: number;
  maxAdmin: number;
  shiftPreference: ShiftPreference;
  nightEligible: boolean;
  adminEligible: boolean;
  /** Community hospitals this physician may be assigned rounders at. MAIN is implicit. */
  eligibleHospitals: Set<Hospital>;
  unavailableDates: Set<string>;
  preferredDates: Set<string>;
}

/** A single shift slot to be filled (13 per calendar day). */
export interface ShiftSlot {
  /** ISO date string (YYYY-MM-DD) the shift starts. */
  date: string;
  /** ISO date string the shift ends (night shifts cross midnight). */
  endDate: string;
  shiftType: ShiftType;
  /** Which hospital this slot belongs to. Community hospitals are rounder-only. */
  hospital: Hospital;
  rounderIndex: number | null;
  startTime: string;
  endTime: string;
  /** Pre-assigned physician (locked or manual) — never overwritten. */
  physicianId: string | null;
  isLocked: boolean;
  isManual: boolean;
}

/** Output assignment after the scheduler runs. */
export interface AssignmentResult extends ShiftSlot {
  isAutoGenerated: boolean;
  warnings: string[];
}

/** Per-physician workload statistics after a run. */
export interface PhysicianStats {
  physicianId: string;
  fullName: string;
  total: number;
  rounding: number;
  admin: number;
  nights: number;
  weekends: number;
  desiredShifts: number;
  minShifts: number;
  maxShifts: number;
  belowMin: boolean;
  aboveMax: boolean;
}

export interface SchedulerResult {
  assignments: AssignmentResult[];
  warnings: string[];
  stats: PhysicianStats[];
  fairnessScore: number;
}

export interface SchedulerOptions {
  /** When true, hard maxShifts cap may be exceeded to fill coverage. */
  allowOverMax?: boolean;
}
