import type { ShiftType, ShiftPreference, Hospital } from "@prisma/client";

/**
 * A physician's scheduling profile — the subset of fields the scheduler
 * needs, plus precomputed availability sets keyed by ISO date string.
 */
export interface SchedulerPhysician {
  id: string;
  fullName: string;
  active: boolean;
  desiredShifts: number;
  minShifts: number;
  maxShifts: number;
  minRounding: number;
  maxRounding: number;
  minNights: number;
  maxNights: number;
  minAdmin: number;
  maxAdmin: number;
  shiftPreference: ShiftPreference;
  nightEligible: boolean;
  adminEligible: boolean;
  /** Community hospitals this physician may be assigned rounders at. MAIN is implicit. */
  eligibleHospitals: Set<Hospital>;
  unavailableDates: Set<string>;
  preferredDates: Set<string>;
  /** ISO dates the physician requested off — a hard block on any shift. */
  timeOffDates: Set<string>;
}

/** A single shift slot to be filled (13 per calendar day). */
export interface ShiftSlot {
  /** ISO date string (YYYY-MM-DD) the shift starts. */
  date: string;
  /** ISO date string the shift ends (night shifts cross midnight). */
  endDate: string;
  shiftType: ShiftType;
  /** Which hospital this slot belongs to. Community hospitals are rounder-only. */
  hospital: Hospital;
  rounderIndex: number | null;
  startTime: string;
  endTime: string;
  /** Pre-assigned physician (locked or manual) — never overwritten. */
  physicianId: string | null;
  isLocked: boolean;
  isManual: boolean;
}

/** Output assignment after the scheduler runs. */
export interface AssignmentResult extends ShiftSlot {
  isAutoGenerated: boolean;
  warnings: string[];
}

/** Per-physician workload statistics after a run. */
export interface PhysicianStats {
  physicianId: string;
  fullName: string;
  total: number;
  rounding: number;
  admin: number;
  nights: number;
  weekends: number;
  desiredShifts: number;
  minShifts: number;
  maxShifts: number;
  belowMin: boolean;
  aboveMax: boolean;
}

/** A slot that no eligible physician could fill (e.g. too many off). */
export interface UnfilledSlot {
  date: string;
  hospital: Hospital;
  shiftType: ShiftType;
  rounderIndex: number | null;
}

export interface SchedulerResult {
  assignments: AssignmentResult[];
  warnings: string[];
  stats: PhysicianStats[];
  fairnessScore: number;
  unfilledSlots: UnfilledSlot[];
}

export interface SchedulerOptions {
  /** When true, hard maxShifts cap may be exceeded to fill coverage. */
  allowOverMax?: boolean;
  /**
   * Night shifts worked on dates OUTSIDE the slot window (e.g. the last days
   * of the prior month) whose two-day post-night rest reaches into the window.
   * Each entry blocks date+1 and date+2 for that physician.
   */
  priorNights?: { physicianId: string; date: string }[];
}
