import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

/**
 * Edit a single assignment. Supports three manual operations:
 *   - change physician (sets physicianId, marks isManual)
 *   - clear the slot   (physicianId = null)
 *   - toggle lock      (isLocked)
 */
export async function PATCH(
  req: Request,
  { params }: { params: { id: string } }
) {
  const body = await req.json();
  const data: Record<string, unknown> = {};

  if ("physicianId" in body) {
    data.physicianId = body.physicianId || null;
    data.isManual = Boolean(body.physicianId);
    data.isAutoGenerated = false;
    // Reassigning by hand clears any stale coverage-gap warning.
    data.warnings = [];
  }
  if ("isLocked" in body) {
    data.isLocked = Boolean(body.isLocked);
  }
  if (body.clear === true) {
    data.physicianId = null;
    data.isManual = false;
    data.isLocked = false;
    data.warnings = [];
  }

  const updated = await prisma.shiftAssignment.update({
    where: { id: params.id },
    data,
    include: { physician: { select: { id: true, fullName: true } } },
  });

  return NextResponse.json({
    id: updated.id,
    physicianId: updated.physicianId,
    physicianName: updated.physician?.fullName ?? null,
    isManual: updated.isManual,
    isLocked: updated.isLocked,
    isAutoGenerated: updated.isAutoGenerated,
    warnings: updated.warnings,
  });
}
